### ISSUE TITLE
Plugin mit Shopware 5.7 kompatibel machen

### ISSUE THREAD

**Issue by iljamobilemojo** [Endereco/endereco-shopware5-client#6]
Aktuell erscheint bei der Installation folgende Fehlermeldung:

```
Ups! Ein Fehler ist aufgetreten! Die nachfolgenden Hinweise sollten Ihnen weiterhelfen. The "endereco_shopware5_client.subscriber.frontend" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead. in vendor/symfony/dependency-injection/Container.php on line 275 Stack trace: #0 vendor/symfony/dependency-injection/Container.php(231): Symfony\Component\DependencyInjection\Container->make() #1 engine/Shopware/Components/DependencyInjection/Container.php(210): Symfony\Component\DependencyInjection\Container->get() #2 engine/Shopware/Components/DependencyInjection/Container.php(134): Shopware\Components\DependencyInjection\Container->doLoad() #3 engine/Shopware/Components/ContainerAwareEventManager.php(191): Shopware\Components\DependencyInjection\Container->get() #4 engine/Shopware/Components/ContainerAwareEventManager.php(138): Shopware\Components\ContainerAwareEventManager->lazyLoad() #5 engine/Library/Enlight/Event/EventManager.php(213): Shopware\Components\ContainerAwareEventManager->getListeners() #6 engine/Library/Enlight/Controller/Action.php(197): Enlight_Event_EventManager->notify() #7 engine/Library/Enlight/Controller/Dispatcher/Default.php(478): Enlight_Controller_Action->dispatch() #8 engine/Library/Enlight/Controller/Front.php(228): Enlight_Controller_Dispatcher_Default->dispatch() #9 engine/Shopware/Kernel.php(189): Enlight_Controller_Front->dispatch() #10 vendor/symfony/http-kernel/HttpCache/SubRequestHandler.php(85): Shopware\Kernel->handle() #11 vendor/symfony/http-kernel/HttpCache/HttpCache.php(477): Symfony\Component\HttpKernel\HttpCache\SubRequestHandler::handle() #12 engine/Shopware/Components/HttpCache/AppCache.php(261): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward() #13 vendor/symfony/http-kernel/HttpCache/HttpCache.php(267): Shopware\Components\HttpCache\AppCache->forward() #14 engine/Shopware/Components/HttpCache/AppCache.php(102): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass() #15 shopware.php(122): Shopware\Components\HttpCache\AppCache->handle() #16 {main}  

```
Die Nutzung des Plugin im 5.7 ist somit nicht möglich.

**Comment by iljamobilemojo** [comment]
Vorläufige Lösung: bei jedem Service in services.xml einen `public="true"` setzen.
